### ISSUE TITLE
Can marks use something other than width for positioning?

### ISSUE THREAD

**Issue by ChuckPierce** [react-component/slider#126]
When positions the marks for the rc-slider it looks like the component uses width.  This is a nice solution however looking at this screen shot you can see the width of the last mark goes outside of the overall width of the slider itself. This mark width is clickable and could cover some other clickable DOM elements if they are close enough to the slider.

![image](https://cloud.githubusercontent.com/assets/7853740/17154663/0b2c4d36-5350-11e6-82d5-2bb2e94c9ede.png)

Would you be opposed to using just straight up positioning (i.e. left and right attrs) instead of using width?  This would solve the issue of the mark clickable area being outside of the overall specified width.  Wondering what you thought / what other contributors think.

**Comment by benjycui** [comment]
Actually, marks use `left` for positioning... https://github.com/react-component/slider/blob/master/src/Marks.jsx#L28

So, the problem is that marks' width is greater than what it need. It's a safe solution for rc-slider doesn't know the real width of a mark.

You can set the width of each marks, see: http://react-component.github.io/slider/examples/marks.html

**Comment by bradennapier** [comment]
This makes things work pretty bad.  Need a better way to position the marks that isn't so difficult.

![image](https://user-images.githubusercontent.com/15365418/29644446-ff505bb8-882a-11e7-9c8e-b6e267939aaf.png)

**Comment by Zodiase** [comment]
The overflow is also causing problems if the parent needs `overflow: auto`.
![image](https://user-images.githubusercontent.com/1815174/38341620-1a9a8866-383f-11e8-8759-9d91b0150436.png)

Using `transform: translateX(-50%)` instead of `margin-left` makes the marks automatically adopt the its own width for centering.
![image](https://user-images.githubusercontent.com/1815174/38341650-4b65a2a0-383f-11e8-94c1-c65471f6a73b.png)
![image](https://user-images.githubusercontent.com/1815174/38341662-59647066-383f-11e8-835f-185f3b32fb73.png)
