### ISSUE TITLE
Logarithmic Range?

### ISSUE THREAD

**Issue by JimmyMultani** [react-component/slider#150]
Hello! Great component!

I was wondering if there was an ability to create a logarithmic range slider?

Thanks!

**Comment by benjycui** [comment]
I don't understand, could you provide an example?

**Comment by just-boris** [comment]
Logarithmic range can be useful when you need to choose between huge values, like here:
![image](https://cloud.githubusercontent.com/assets/812240/18506550/dc424e3c-7a6c-11e6-9e89-ae54cacd4370.png)

I had the same issue, but I have worked around using `values` array instead of `min` and `max`

```jsx
<Slider marks={['10', '100', '1000', '10k', '100k']} values={[10, 100, 1000, 10000, 100000]} />
```

@JimmyMultani will it work for you?

**Comment by JimmyMultani** [comment]
Hey @just-boris, 

Your code doesn't seem to work for me. The `marks` prop doesn't seem to follow the requirement for `rc-slider`.

Can you show me an example please?

Thanks!

**Comment by benjycui** [comment]
@JimmyMultani http://react-component.github.io/slider/examples/marks.html

@just-boris it seems that you need to upgrade you rc-slider 😄

**Comment by lk-jeffpeck** [comment]
Is it possible to do this with the current version of rc-slider?
