### ISSUE TITLE
Is there anyway to create a minimum distance between two handles? 

### ISSUE THREAD

**Issue by tinder-jpeng** [react-component/slider#177]
Say I wanted to make a range slider with two handles, but the two handles have to be at least a min distance apart. If the user tries to slide the handle to close the distance, the handle will be disabled to prevent the user from decreasing the range. I tried implementing this using pushable, but it seems like although the min distance of the values is enforced, the handles are still enabled. Is there a suggested way on doing this?

**Comment by benjycui** [comment]
`value` is a controlled property https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by tinder-jpeng** [comment]
Thank you!

**Comment by Noitidart** [comment]
@benjycui @tinder-jpeng if we do controlled though, then we have to handle the "pushable" part our selves. By default, when pushable is true, the min gap is step of 1. Is it possible to control that? I created a min gap here of 4 steps, but its not pushable anymore due to the controlled nature - https://noitidart.github.io/slid/index.html

**Comment by howardya** [comment]
@Noitidart I am trying to make it pushable and yet controlled by onChange props. It does not work. Why is this not possible?
