### ISSUE TITLE
How do I reset values for slider

### ISSUE THREAD

**Issue by doshisunny** [react-component/slider#202]
I have a slider as below which uses marks for custom dates.
Sliding functionality is working. Once slider moves and certain point I want to reset slider to defult values after some action (For e.g Button click).

There is not reset or custom method option in props which I can use. 
What is the best way to do that?

Original Slider :
<img width="879" alt="screen shot 2017-01-10 at 3 13 36 pm" src="https://cloud.githubusercontent.com/assets/12001907/21825018/9a1756c8-d747-11e6-843b-69a9e43cf372.png">

User Changes Slider to : 
<img width="865" alt="screen shot 2017-01-10 at 3 20 26 pm" src="https://cloud.githubusercontent.com/assets/12001907/21825222/7313f9d6-d748-11e6-97b4-e0ccd04e5372.png">

After reset button click it need to go back to : 
<img width="879" alt="screen shot 2017-01-10 at 3 13 36 pm" src="https://cloud.githubusercontent.com/assets/12001907/21825018/9a1756c8-d747-11e6-843b-69a9e43cf372.png">

**Comment by yesmeck** [comment]
Use prop `value`  to convert Slider to a [controlled component](https://facebook.github.io/react/docs/forms.html#controlled-components).

**Comment by sandervanhooft** [comment]
I have the same issue. As soon as I use the `value` prop, I am unable to grab the slider handles.

@yesmeck Do you perhaps have an example solution for this use case specific to `rc-slider`?

**Comment by yesmeck** [comment]
@sandervanhooft See https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-action

**Comment by icambron** [comment]
@yesmeck This is a little bit confusing. Changing `defaultValue` makes a lot of sense, but the component's `componentWillReceiveProps()` ignores changes to `defaultValue`. Thus the component won't rerender. Is this a bug, or expected behavior? If the it's expected, then I'm confused on how to accomplish the goal outlined by the OP.

**Comment by yesmeck** [comment]
`defaultValue` is not considered to change, if you want change value of slider, use `value`. See 

https://facebook.github.io/react/docs/forms.html#controlled-components
https://facebook.github.io/react/docs/uncontrolled-components.html

**Comment by icambron** [comment]
@yesmeck but if I set `value` the user can't make further edits. Here is a [fiddle](http://codepen.io/anon/pen/EWzPgp?editors=0010): if I change `defaultValue` to `value` then slider is locked in place. Perhaps I'm being dense, but I don't see how using an uncontrolled component would help, since then I wouldn't be able to actually set it. ([Another fiddle](http://codepen.io/anon/pen/rygxJZ?editors=0010)). What am I missing?

**Comment by yesmeck** [comment]
> but I don't see how using an uncontrolled component would help

Then you should use controlled component.

**Comment by icambron** [comment]
@yesmeck that's my first fiddle though, right? I think I must be missing something more basic here.

**Comment by yesmeck** [comment]
No, your first fiddle is still a uncontrolled component. A controlled component means you pass `value` to the component and use `onChange` to collect the component value to the `state`.

See http://codepen.io/yesmeck/pen/evaJPP?editors=0010

**Comment by icambron** [comment]
Ah, OK, I get it now. Thanks for your time!

**Comment by linatoquica93** [comment]
@yesmeck  thanks, I implemented and it works so fine!

**Comment by bodfaj13** [comment]
> No, your first fiddle is still a uncontrolled component. A controlled component means you pass `value` to the component and use `onChange` to collect the component value to the `state`.
> 
> See http://codepen.io/yesmeck/pen/evaJPP?editors=0010

awesome, thanks!

**Comment by udayanbk** [comment]
I just faced this issue in my project. Following solution may help you.

Scenario: The project is in React-nextJS framework. We have to use recommended client components. There is price slider component called as RangeSelector on one page. The issue was that on resetting that RangeSelector, functionally wise it works well but on slider it was showing same last searched values and slider point tip. that is it was showing previous min max values. 

Solution: 
IRange selector is in child component. n RangeSelector component, two JSX attributes - key, onAfterChange - used like:
key={onReseTrue} & onAfterChange(e, props.min_val, props.max_val) }}, it is defined in main component as follows:
`function onAfterChange(data,minVal,maxVal) {
        data.minval=minVal;
        data.maxval=maxVal;
    }`    
Important :  We used a prop "key" in RangeSelector slider component and set its value true on clicking reset button. 
Pass both these values as props to child component.

**Comment by RichardLanham** [comment]
Is there a way to set the value of a MUI (v1) Slider in a function, without using a value prop? Because the value prop makes it impossible to drag the thumb. It would be more useful to be able to set the Slider value in a function, so the thumb moves. Looking at the package Slider.d.ts file, there doesn't seem to be a way to do that.

Slider.defaultValue is set, but Slider.value is omitted.
1. User drags the thumb, 
2. onChange fires out a value, 
3. doSomethingWith(value).
4. User clicks a "Reset"  button, onClick => Reset Slider.value --> thumb moves back to org tick

Step #4 doesn't seem possible. I can reset everything I used that Slider value to set, except the Slider. There doesn't seem a way to write a method to move the thumb.
