### ISSUE TITLE
custom hadleStyle hover state

### ISSUE THREAD

**Issue by maxww** [react-component/slider#295]
Is there a way to change hadleStyle hover state css?

**Comment by paranoidjk** [comment]
override css？

**Comment by jonmase** [comment]
e.g. 
.rc-slider-handle:active {
    box-shadow: 0 0 5px red;
}

Would be nice to be able to do this using an activeHandleStyle property, so we could use theme colour variables. I'm using Material UI, so would like to use the theme colour from that, rather than having to remember to change the value in CSS. I can have a crack at this when I've got some time, but don't hold your breath and very happy for someone else to get there first :-)

**Comment by benjycui** [comment]
> Would be nice to be able to do this using an activeHandleStyle property

Nope.

**Comment by benjycui** [comment]
@jonmase you can use custom handle to achieve this.
