### ISSUE TITLE
Tooltip formatter

### ISSUE THREAD

**Issue by thorbenziemek** [react-component/slider#32]
It would be nice to be able to format the tooltip's contents.

**Comment by coniel** [comment]
Also, it would be nice to be able to disable the tooltip.

**Comment by benjycui** [comment]
@coniel do you mean that `rc-slider` should provide a prop to hide tooltip?

**Comment by coniel** [comment]
@benjycui Yep, basically just expose the `noTip` prop on the Handle up to the Slider component.

**Comment by just-boris** [comment]
@coniel @benjycui I have a better solution. What about prop like `handleComponent`?  By default, the bundled Handle component will be used, but it would be possible to replace to different implementation. 

It is makes sense for me, because I need to create slider with the following view:

![image](https://cloud.githubusercontent.com/assets/812240/11165985/b4d4c7b4-8b32-11e5-8324-a30ad58bb2c8.png)

Now I can do it only by patching this lib, but then I can configure handle view via configuration prop and it  makes possible to create any design of slider.

**Comment by benjycui** [comment]
@just-boris It is reasonable. What is your opinio? @yiminghe @simaQ 

@coniel Next time, you should open a new issue to discuss a new feature. It is weirdo to discuss two different features in one issue. Though they are relative.

**Comment by yiminghe** [comment]
ok with tipFormatter
