### ISSUE TITLE
Range slider issue, when min value is more than max value and also more than aria-valuemax value

### ISSUE THREAD

**Issue by karthik2706** [react-component/slider#395]
![2018-02-05_18-01-07](https://user-images.githubusercontent.com/6582215/35804712-e2a836ce-0a9e-11e8-90f1-3564e8b64f36.gif)

**Comment by Robin-front** [comment]
https://github.com/react-component/slider/blob/c67e422c03790f864e672e976407617c6f844374/src/Range.jsx#L273
Because here has a bug. When you click Apply button, the variable handle is null, so this function will skip condition judge and return the new value 100. But it should actually return 40 for this example. 

trace these fixed pr but not yet merge: #304 #379

**Comment by yesmeck** [comment]
#304 has been merged, try 8.6.1
