### ISSUE TITLE
Range is not updated on state change

### ISSUE THREAD

**Issue by ka7eh** [react-component/slider#518]
React: 16.7.0 + rc-slider:8.6.4

I have a slider range and on update its value is saved in the state. If I change the state via other inputs, the slider does not update.

Here is an example: https://jsfiddle.net/0yb3z7hf/1/
If you change the values in inputs boxes, nothing happens to the slider.

Strangely enough, if you remove the value prop on the `Range` component and turn it into an uncontrolled component, then it works, which is unexpected. Though first you have to move one of the handles and then change the input boxes to see the effect.

**Comment by klinkow** [comment]
This bug starts appearing after version 8.1.3.

**Comment by DarrylD** [comment]
Still having this issue (regardless of controlled or uncontrolled), any idea on a fix before I deep dive?

**Comment by mihalo** [comment]
Same problem for me, any fixes or work arounds?

**Comment by alvinbabujohn** [comment]
Have a similar issue with a form input couping: 
https://codesandbox.io/s/rc-slider-bootstrap-input-test-57rux

**Comment by Thebarda** [comment]
Having same issue

**Comment by alerg11** [comment]
I had this same issue and found a solution, maybe is not the finest but it works, at least until this issue gets fixed in the library. 

You could add a `key` prop to the `<Range>` component with a dynamic value (`Date.now()` for example), and every time you change the state you need for updating the Slider, you also update this key prop with a new value ( `Date.now()` ).

This will "destroy" the `<Range>` component and create another one new with the new values you need, so the rendering works just fine.

I modified @alvinbabujohn example to show how it is.. 
https://codesandbox.io/s/rc-slider-bootstrap-input-test-fv46b

Hope it helps.

**Comment by murfett-au** [comment]
Nice (while from a react point of view - not-so-nice) work around @alerg11. Insetad of using `key={Date.now()` I used `key={value}` where value is the same varibale I pass as prop `value-{value}`. I figure this will only re-render when the value changes, not every time any other state value in any ancestor component changes.

**Comment by murfett-au** [comment]
I experienced this issue, but found it was caused by me having a <RangeWrapper> compomnent around my <Range> component, and although I passed the `value` prop to the <RangeWrapper> component, I did not pass the value prop from down to the <Range> component. I fixed by adding a prop like this over-simplified code:
```
function RangeWrapper({ value, setValue}) {
  return <Range
    value={value} // This was the missing prop causing this behaviour - it was not a bug
    ...
...
```

**Comment by klinkow** [comment]
@murfett-au , thanks for contributing but I think your issue is different from the one shared by the original post. If you visit the jsfiddle in the original post it does not appear to contain the problem you've described.

**Comment by ka7eh** [comment]
I tested again with the latest version (9.7.2) and looks like the issue is now resolved. I'm closing this report.

**Comment by alexandermirzoyan** [comment]
> I had this same issue and found a solution, maybe is not the finest but it works, at least until this issue gets fixed in the library.
> 
> You could add a `key` prop to the `<Range>` component with a dynamic value (`Date.now()` for example), and every time you change the state you need for updating the Slider, you also update this key prop with a new value ( `Date.now()` ).
> 
> This will "destroy" the `<Range>` component and create another one new with the new values you need, so the rendering works just fine.
> 
> I modified @alvinbabujohn example to show how it is.. https://codesandbox.io/s/rc-slider-bootstrap-input-test-fv46b
> 
> Hope it helps.

Thank you so much, it even helped me in 2023 :)
