### ISSUE TITLE
Replace deprecated lifecycle componentWillReceiveProps

### ISSUE THREAD

**Issue by evoyy** [react-component/slider#562]
This lifecycle method is in the following components:

https://github.com/react-component/slider/blob/master/src/Slider.jsx
https://github.com/react-component/slider/blob/master/src/Range.jsx

We need to replace it in advance of React 17. Depending on how important performance is considered here, we could simply move the logic to componentDidUpdate at the expense of some extra renders.

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#migrating-from-legacy-lifecycles

**Comment by captbaritone** [comment]
It's worth noting that this issue is blocking anyone who is using `rc-slider` from adopting `<React.Strict>` in the portions of their app which make use of `rc-slider`.

**Comment by afc163** [comment]
PR is welcome~

**Comment by julien-jean** [comment]
I started working on a solution with `componentDidUpdate`.  (see PR : #587 )

There are two points that I'd like to mention:

* `setState` is not allowed inside `componentDidUpdate` (eslint rule : `react/no-did-update-set-state`)
* I've updated the `Range.test.js` to be fully working but I'm not really convinced we need a `TestParent` component to ensure the Range is correctly behaving.

**Comment by Simbul** [comment]
Would you consider a PR that just [renames](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods) the methods to `UNSAFE_componentWillReceiveProps `, in order to silence the warnings that come up in React 16.9+ while a proper fix is concocted and applied? I'm happy to produce one if you think it's worth it.

For context, the `UNSAFE` version of the method has been available since React 16.3 (March 2018).
