### ISSUE TITLE
Cannot test with react-testing-library

### ISSUE THREAD

**Issue by javillerenas** [react-component/slider#661]
### Description
Hi, I've been working on testing a component which contains multiple `<Range>` components with [`@react-testing-library`](https://github.com/testing-library/react-testing-library) and are having issues attempting to programmatically changing the value of the slider. Specifically I cannot replicate a focus and keydown user event.

### Code
This is what my code looks like:
```ts
...
const sliders1 = within(rows[0]).getAllByRole("slider");
await act(async () => {
  fireEvent.focus(sliders1[1]);
  console.log('Slider after focus: \n', prettyDOM(sliders1[1]));
  fireEvent.keyDown(sliders1[1], { key: 'ArrowRight', code: 'ArrowRight' });
  fireEvent.keyDown(sliders1[1], { key: 'ArrowRight', code: 'ArrowRight' });
  console.log('Slider after KeyDown: \n', prettyDOM(sliders1[1]));
});
```

These are the results of the `console.log()` calls:
```html
Slider after focus:  
    <div
      aria-disabled="false"
      aria-valuemax="60"
      aria-valuemin="0.5"
      aria-valuenow="30.5"
      class="rc-slider-handle rc-slider-handle-2"
      role="slider"
      style="left: 50.42016806722689%; transform: translateX(-50%);"
      tabindex="0"
    />

Slider after KeyDown:  
    <div
      aria-disabled="false"
      aria-valuemax="60"
      aria-valuemin="0.5"
      aria-valuenow="30.5"
      class="rc-slider-handle rc-slider-handle-2"
      role="slider"
      style="left: 50.42016806722689%; transform: translateX(-50%);"
      tabindex="0"
    />
```

As you can see, the `valuenow` is the same before and after the `keyDown` event. Also I noticed the `rc-slider-handle-dragging` class is not present.

The code below shows how I am currently rendering the `<Range>` component:
```html
<Range
  min={limitsMin}
  max={limitMax}
  step={0.5}
  value={row.value}
  allowCross={false}
  onChange={(e: any) => handleSliderChange(e, index)}
  marks={getRangeMarks(row)}
  data-testid="range-height"
/>
```

#### __NOTE 1:__ 
The Range's __`onChange`__ handler is triggered, but the event contains the same exact values the `<Range>` currently has which is :`[0.5, 30.5, 60]` (There's no change in the actual values).

#### __NOTE 2:__ 
The class __`rc-slider-handle-dragging`__ is present in the first slider even though I never set it myself. If I try to fire a `keyDown` event it does not work either.

### Update 1:
Looking at both the `container.baseElement` and the actual Range, they both have a `clientHeight` and `clientWidth` of `0`. Not sure if that might be causing the issues.

### Environment
* `rc-slider`: "9.2.4"
* `@types/rc-slider`: "^8.6.5"
* `@testing-library/react`: "^9.5.0"
* `@testing-library/jest-dom`: "^4.2.4"

**Comment by mstrofbass** [comment]
Note that in the library tests, which use enzyme, the focus event is fired on the slider component itself, not the handle, which is what the getByRole returns, I believe. Might try adjusting based on that.

I messed around with some basic tests a bit but couldn't get it to work and have more pressing things to do, but wanted to point that out just in case it was helpful.

**Comment by rcidaleassumpo** [comment]
Just wanted to leave here my 2 cents about this situation. 
When using this component, or any component that is not easy and straight forward to test, by straight forward I mean, it just works. Just mock the functionality that you need. 

```
jest.mock('rc-slider', () => (props) => {
  const { marks, onAfterChange } = props
  return (
    <div>
      {Object.entries(marks).map(([number, component], ind) => {
        return (
          <span
            key={ind}
            onClick={() => {
              onAfterChange(Number(number))
            }}
          >
            {component}
          </span>
        )
      })}
    </div>
  )
})
```
Don't waste your time trying to go about how the library should work with x,y,z test library, it doesn't matter. In the unit test, you don't care about the way this component is rendering, you just care about 
- Click in the mark
- whatever eventHandler you are using was fired with the mark
That's it. 
In my opinion, you shouldn't even be testing how it renders, otherwise you are testing react. Or if you want to go that route, just use a snapshot in a separate test to assert the how it looks when it renders. 
By going deep into which event is fired by the library, you are linking to their implementation, and that's their job. 
To finish, I'm not a part of this library, have nothing to do with it, just wanted to make sure that other people that might have been struggling to making custom components work, be "free". 
As for the library, you are doing a great job, thanks mate.

**Comment by rcidaleassumpo** [comment]
Another note, this approach could maybe bite you in the ass, if the library decides to instead of returning a number, returns for some reason, an object. But again, it's your fault, because first, you should be using typescript, then it would break in compile time, and second if you use a library, update the version, and don't read the release notes, please do it :), to put it nicely.
