### ISSUE TITLE
Mark labels overflow slider width

### ISSUE THREAD

**Issue by vdh** [react-component/slider#76]
Due to the way the labels are positioned with `position: absolute` and percentage widths, the labels are very often overflowing very badly off the left and right edges of their container, especially if very long label text is used.

**Comment by just-boris** [comment]
Confirm that issue, but I don't see here an easy fix.
As I understand, we need to compute `markWidth` [here](https://github.com/react-component/slider/blob/master/src/Marks.jsx#L8) for each mark regarding its content. Also, because of React Virtual DOM we don't have access to real DOM-nodes to get actual sizes of marks.

So, we need to refactor here and arrange marks on `componentDidMount`, where we can get their actual DOM-nodes and arrange them properly.

@vdh if you will try to something in this way, it will be much appreciated.

**Comment by just-boris** [comment]
Also, we have a got a pull-request #78 that possibly can fix your issue

**Comment by benjycui** [comment]
3.4.0
